# Generated by Django 3.0.8 on 2020-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_face_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='face_2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Faces'),
        ),
        migrations.AddField(
            model_name='users',
            name='voice',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Voices'),
        ),
    ]
