# Generated by Django 3.0.8 on 2020-10-17 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20201016_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersVoiceTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.FileField(blank=True, default=None, null=True, upload_to='VoicesTry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voz',
                'verbose_name_plural': 'Voces',
            },
        ),
    ]
