# Generated by Django 3.0.8 on 2020-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usersvoicetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersvoicetry',
            name='created_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
