# Generated by Django 3.0.8 on 2020-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20201018_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
